In [1]:
import pandas as pd

In [19]:
data = pd.read_csv('Data/elsdev2016mex.csv')
vals = pd.read_csv('Values/Els_Valores.csv')

In [20]:
vals = vals[vals['Variable']=='p34m']

In [21]:
for index, row in data.iterrows():
    for index2, row2 in vals.iterrows():
        if row['p34m'] == row2['Valor']:
            row['p34m'] == row2['Descripción']

In [23]:
data[['p34m']]

       p34m
0     30003
1     19039
2      7101
3      7065
4      7089
5      7089
6     20014
7      7040
8      7089
9      7052
10    20014
11     7069
12     9010
13    20014
14     7040
15    26030
16     7009
17     7089
18    30003
19     7069
20     7065
21     9006
22     7069
23     7101
24    21114
25    20014
26     7101
27     9010
28     7101
29    11001
...     ...
3105  28038
3106  30003
3107   7040
3108  11007
3109  30003
3110  30003
3111  30003
3112  28032
3113  24028
3114  30174
3115  24028
3116  30174
3117  19039
3118  30003
3119  30003
3120   7009
3121   7009
3122  21114
3123   7101
3124   7009
3125   7089
3126   7097
3127   7069
3128   7101
3129   7101
3130   7089
3131  19039
3132  30003
3133   7089
3134   7097

[3135 rows x 1 columns]